import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const styleDescriptions: Record<string, string> = {
  modern: 'sleek contemporary design with gradients and depth, tech-forward aesthetic',
  minimalist: 'ultra-simple clean lines, flat design, minimal details, monochromatic with accent color',
  colorful: 'vibrant rich colors, dynamic composition, eye-catching palette, bold and expressive',
  realistic: 'detailed photorealistic medical illustration, anatomically accurate, professional medical textbook style'
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { title, description, style = 'modern' } = await req.json();
    
    if (!title) {
      return new Response(
        JSON.stringify({ error: 'Treatment title is required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    console.log(`Generating ${style} icon for treatment: ${title}`);

    const styleDesc = styleDescriptions[style] || styleDescriptions.modern;

    // Generate a professional medical icon using Lovable AI with PNG format
    const prompt = `Create a ${styleDesc} medical icon representing ${title}. ${description ? `Context: ${description}.` : ''} Style requirements: ${styleDesc}, professional healthcare aesthetic, centered composition, transparent or white background, PNG format with clean edges, 512x512 icon. Color scheme should incorporate burgundy/maroon tones (#944242) as accent color where appropriate for the ${style} style. Output must be suitable for web display with transparency support.`;

    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages: [
          {
            role: 'user',
            content: prompt
          }
        ],
        modalities: ['image', 'text']
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Lovable AI error:', response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: 'Rate limit exceeded. Please try again later.' }),
          { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: 'AI credits depleted. Please add credits to your workspace.' }),
          { status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }

      throw new Error(`AI gateway error: ${response.status}`);
    }

    const data = await response.json();
    console.log('AI Response structure:', JSON.stringify(data, null, 2));

    // Check for different response formats
    let imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    
    // Alternative format check
    if (!imageUrl && data.choices?.[0]?.message?.content) {
      console.log('Checking alternative format...');
      // Sometimes the image might be in content
      const content = data.choices[0].message.content;
      if (typeof content === 'string' && content.startsWith('data:image')) {
        imageUrl = content;
      }
    }

    if (!imageUrl) {
      console.error('No image found in response. Full response:', JSON.stringify(data));
      throw new Error('No image generated by AI. Response structure may have changed.');
    }

    console.log('Icon generated successfully');

    return new Response(
      JSON.stringify({ imageData: imageUrl }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in generate-treatment-icon:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
