// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zidstpdifzldgrnjkxwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppZHN0cGRpZnpsZGdybmpreHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MzYyNTcsImV4cCI6MjA3NzUxMjI1N30.kfMLh-8ak4eVH7N9xI1bTyG1akFq0ecIVAbHPLvlMwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});