// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zidstpdifzldgrnjkxwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppZHN0cGRpZnpsZGdybmpreHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MzYyNTcsImV4cCI6MjA3NzUxMjI1N30.kfMLh-8ak4eVH7N9xI1bTyG1akFq0ecIVAbHPLvlMwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use sessionStorage so the admin session is cleared when the browser
// (or tab) is closed, instead of persisting indefinitely in localStorage.
// This way an admin who forgets to log out won't leave their account open
// the next time the browser is started.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});